version: '3.4'

services:

  app:
    build:
      context: .
      target: dev
    ports:
      - 3030:3030
      - 9229:9229
    image: koa-server:dev
    command: [ "npm", "run", "watch" ]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3030
    networks:
      - backend

  test:
    build:
      context: .
      target: test
    image: koa-server:test
    command: [ "npm", "t" ]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: test
      PORT: 3000
    networks:
      - backend

networks:
  backend:
    driver: bridge
