version: 2.1
orbs:
  node: circleci/node@1.1.6
workflows:
  build-and-test:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12
    environment:
      NODE_ENV: test
      JWT_SECRET: secret
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
